#!/usr/bin/env python3
"""
Generate a Dakota input file from params.yml.

Usage:
    python generate_dakota_in.py            # dakota.in (EGO + pattern-search)
    python generate_dakota_in.py --bayes    # dakota_bayes.in (DREAM, needs
                                            #   cannon_logq_obs.dat first)
"""

import argparse
import yaml
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--bayes', action='store_true',
                    help='emit dakota_bayes.in (bayes_calibration dream) '
                         'instead of the optimisation input')
ARGS = parser.parse_args()

with open('params.yml') as f:
    cfg = yaml.safe_load(f)

dakota  = cfg['dakota']
modules = cfg.get('modules', {})

# Parameters owned by each module: disabled module → parameter fixed regardless
# of its own active flag.
_MODULE_PARAMS = {
    'snowpack':      ['PDD_melt_factor'],
    'frozen_ground': ['log__fdd_threshold', 'snow_insulation_k'],
    'direct_runoff': ['f_direct_runoff'],
    'rain_on_snow':  [],
}
for mod, param_names in _MODULE_PARAMS.items():
    if not modules.get(mod, True):
        for name in param_names:
            if name in cfg['parameters']:
                cfg['parameters'][name]['active'] = False

active  = {name: p for name, p in cfg['parameters'].items() if p['active']}
n       = len(active)

desc_str    = ' '.join(f"'{name}'" for name in active)
lower_str   = '  '.join(str(p['lower'])   for p in active.values())
upper_str   = '  '.join(str(p['upper'])   for p in active.values())
initial_str = '  '.join(str(p['initial']) for p in active.values())

param_comments = '\n'.join(
    f'#   {name}: {p["description"]}' for name, p in active.items()
)
inactive = {name: p for name, p in cfg['parameters'].items() if not p['active']}
fixed_comments = (
    '\n# Fixed (inactive) parameters:\n' +
    '\n'.join(f'#   {name} = {p["fixed"]}  ({p["description"]})'
              for name, p in inactive.items())
) if inactive else ''

content = f"""\
# Dakota input file: MNiShed Cannon River parameter calibration
# Generated by generate_dakota_in.py from params.yml — do not edit by hand.
#
# Active parameters ({n}):
{param_comments}{fixed_comments}

environment
  top_method_pointer = 'HYBRID'
  tabular_data
    tabular_data_file = 'dakota.dat'

method
  id_method = 'HYBRID'
  hybrid sequential
    method_pointer_list = 'EGO' 'PS'

method
  id_method = 'EGO'
  efficient_global
    gaussian_process surfpack
    initial_samples = {dakota['ego_initial_samples']}
    seed = {dakota['ego_seed']}
    output quiet
  model_pointer = 'M1'

method
  id_method = 'PS'
  coliny_pattern_search
    max_function_evaluations = {dakota['ps_max_evaluations']}
    convergence_tolerance = {dakota['ps_convergence_tolerance']}
    output quiet
  model_pointer = 'M1'

model
  id_model = 'M1'
  single
    interface_pointer = 'I1'
  variables_pointer = 'V1'
  responses_pointer = 'R1'

variables
  id_variables = 'V1'
  continuous_design = {n}
    descriptors   = {desc_str}
    lower_bounds  =  {lower_str}
    upper_bounds  =  {upper_str}
    initial_point =  {initial_str}

interface
  id_interface = 'I1'
  analysis_driver = 'bash run_driver.sh'
  fork
    parameters_file = 'params.in'
    results_file    = 'results.out'
    work_directory
      named 'out/run'
      directory_tag
      directory_save
    file_save
    copy_files 'driver.py' 'cannon_cfg_template.yml' 'CannonTestInput.csv' 'run_driver.sh' 'params.yml'
    asynchronous
      evaluation_concurrency = {dakota['evaluation_concurrency']}

responses
  id_responses = 'R1'
  objective_functions = 1
    response_descriptors = 'neg_kge'
  no_gradients
  no_hessians
"""

bayes_content = None
if ARGS.bayes:
    obs_file = Path('cannon_logq_obs.dat')
    if not obs_file.exists():
        raise SystemExit(
            "cannon_logq_obs.dat not found — run `python make_bayes_data.py` "
            "first to write the observed log-flow calibration data.")
    n_terms = sum(1 for line in obs_file.read_text().splitlines()
                  if line.strip())
    chain_samples = dakota.get('bayes_chain_samples', 20000)
    bayes_content = f"""\
# Dakota input file: MNiShed Cannon River Bayesian (DREAM) calibration
# Generated by `generate_dakota_in.py --bayes` from params.yml — do not edit.
#
# Active parameters ({n}) with uniform priors over their bounds:
{param_comments}{fixed_comments}
#
# Likelihood: Gaussian on the {n_terms} scored log-flow residuals
# (driver_bayes.py returns modelled log-flows; cannon_logq_obs.dat holds the
# observed log-flows); the error scale is inferred (calibrate_error_multipliers).

environment
  tabular_data
    tabular_data_file = 'dakota_bayes.dat'

method
  bayes_calibration dream
    chain_samples = {chain_samples}
    seed = {dakota['ego_seed']}
    calibrate_error_multipliers one
  model_pointer = 'M1'

model
  id_model = 'M1'
  single
    interface_pointer = 'I1'
  variables_pointer = 'V1'
  responses_pointer = 'R1'

variables
  id_variables = 'V1'
  uniform_uncertain = {n}
    descriptors   = {desc_str}
    lower_bounds  =  {lower_str}
    upper_bounds  =  {upper_str}
    initial_point =  {initial_str}

interface
  id_interface = 'I1'
  analysis_driver = 'bash run_driver_bayes.sh'
  fork
    parameters_file = 'params.in'
    results_file    = 'results.out'
    work_directory
      named 'out_bayes/run'
      directory_tag
      directory_save
    file_save
    copy_files 'driver_bayes.py' 'cannon_cfg_template.yml' 'CannonTestInput.csv' 'run_driver_bayes.sh' 'params.yml' 'cannon_logq_obs.dat'
    asynchronous
      evaluation_concurrency = {dakota['evaluation_concurrency']}

responses
  id_responses = 'R1'
  calibration_terms = {n_terms}
    calibration_data_file = 'cannon_logq_obs.dat'
      freeform
  no_gradients
  no_hessians
"""

if bayes_content is not None:
    Path('dakota_bayes.in').write_text(bayes_content)
    print(f"Wrote dakota_bayes.in  ({n} parameters, {n_terms} calibration "
          f"terms)")
else:
    Path('dakota.in').write_text(content)
    print(f"Wrote dakota.in  ({n} active parameters)")
    if inactive:
        print(f"Fixed parameters: {', '.join(inactive)}")
